export enum ActionTypes {
  LOAD_ROOMS = "LOAD_ROOMS",
  LOAD_ROOMS_SUCCESS = "LOAD_ROOMS_SUCCESS",
  LOAD_ROOMS_ERROR = "LOAD_ROOMS_ERROR",
  ADD_RESERVATIONS = "ADD_RESERVATIONS",
  ADD_RESERVATIONS_SUCCESS = "ADD_RESERVATIONS_SUCCESS",
  ADD_RESERVATIONS_ERROR = "ADD_RESERVATIONS_ERROR",
}
